### PR TITLE
[IMP] Add de-DE translation

### PR DESCRIPTION
**Pull request by zero-24**
Dear @Spudley with this PR I suggest an German translation of your plugin

This includes:
- de-DE translation

### CODE REVIEW

**Comment by zero-24** [comment]
Please note that the translated language strings are up-to-date with the changes applied to the original files here: https://github.com/Spudley/plg_user_hibp/pull/4

**Comment by Spudley** [comment]
Awesome, thank you for all your time with this and the other PRs.  👍   Merged.

**Comment by Spudley** [comment]
I'll make a new release with your changes soon.

**Comment by zero-24** [comment]
> Awesome, thank you for all your time with this and the other PRs. 👍 Merged.

Thanks for your time reviewing, testing and merging my changes. Very much appreciated 👍 

> I'll make a new release with your changes soon.

Great 👍

**Comment by Spudley** [comment]
Just to say, I've finally gotten round to actually publishing a release with your changes. Really sorry it took so long. I've had a crazy month.

Thanks again for the contributions. Very much appreciated  :+1:

**Comment by zero-24** [comment]
Thanks and no problem I know that feeling myself too. :-)

**Pull request merged**
