### PR TITLE
[IMP] Apply some php improvments including doc blocks

### PR DESCRIPTION
**Pull request by zero-24**
Dear @Spudley with this PR I suggest some php improvments including doc blocks

This includes:
- doc blocks
- php code style updates
- joomla coding standard updates

### CODE REVIEW

**Comment by Spudley** [comment]
Thank you for this PR. Very much appreciated.

A couple of points:

Firstly, I notice you added a `return false` after the `throw()`. Having a `return` here is pointless as the `throw` breaks you out of the flow. In fact, my IDE is highlighting the `return` as a mistake due to it being unreachable. It should be removed.

Secondly, I appreciate you switching to tabs to make it consistent with Joomla. I would have preferred to stick with spaces, but it's not a battle I'm going to fight with anyone.

Please remove the unecessary `return` statement, and I will merge be happy to merge this PR.

Thank you.

**Comment by zero-24** [comment]
Done.

> Secondly, I appreciate you switching to tabs to make it consistent with Joomla. I would have preferred to stick with spaces, but it's not a battle I'm going to fight with anyone.

Well fine for me. It is just one click in my IDE. It is your plugin. I personally more like tabs but I'm also fine with spaces but mixing it up makes it more difficult to read in my perspective.

**Comment by zero-24** [comment]
So say how you want it to be and I'm happy to implement the requested change.

**Comment by Spudley** [comment]
Thanks for `return` change. Don't worry about the tabs/spaces thing; I'll take it as it is.  👍

**Comment by zero-24** [comment]
Ok fine for me.

**Pull request merged**
