### PR TITLE
[IMP] Apply some codestyle changes to the update server xml file

### PR DESCRIPTION
**Pull request by zero-24**
Dear @Spudley with this PR I suggest some small codestyle changes to your update server xml file. 

This includes:
- spaces to tabs conversation
- reorder the fields
- fix the field value for the `client` attribute
- add the update tags
- add `maintainer` tag
- add `maintainerurl` tag

### CODE REVIEW

**Comment by Spudley** [comment]
Thank you for this PR. Very much appreciated. I have merged it in to master. I will release a new version shortly.

**Comment by zero-24** [comment]
Thanks for merging.

> I will release a new version shortly.

Great please consider the other PR's I did for that new release too :)
https://github.com/Spudley/plg_user_hibp/pulls

**Comment by Spudley** [comment]
Indeed, I'm reviewing them as I have time :-)

**Comment by zero-24** [comment]
Thank you very much. Your work is very appreciated too. 👍

**Pull request merged**
